# Generated by Django 4.0.1 on 2022-01-24 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DIY_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='video_url',
            new_name='video_id',
        ),
    ]
